import os
from dotenv import load_dotenv

load_dotenv()
# Telegram
BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")
TELEGRAM_ALLOWED_USERS = {
    int(uid.strip())
    for uid in os.getenv("TELEGRAM_ALLOWED_USERS", "").split(",")
    if uid.strip().isdigit()
}

# OCR.Space
OCR_SPACE_API_KEY = os.getenv("OCR_SPACE_API_KEY", "helloworld")

# Google
GOOGLE_DRIVE_SHEETS_FOLDER_ID = os.getenv("GOOGLE_DRIVE_SHEETS_FOLDER_ID", "YOUR_GOOGLE_DRIVE_SHEETS_FOLDER_ID")
GOOGLE_DRIVE_IMAGES_FOLDER_ID = os.getenv("GOOGLE_DRIVE_IMAGES_FOLDER_ID", "YOUR_GOOGLE_DRIVE_IMAGES_FOLDER_ID")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "YOUR_GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "YOUR_GOOGLE_CLIENT_SECRET")
GOOGLE_REFRESH_TOKEN = os.getenv("GOOGLE_REFRESH_TOKEN", "YOUR_GOOGLE_REFRESH_TOKEN")

#Openrouter
OPENROUTER_MODEL_NAME = os.getenv("OPENROUTER_MODEL_NAME", "YOUR_OPENROUTER_MODEL_NAME")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "YOUR_OPENROUTER_API_KEY")

# logging
ENABLE_LOGS = os.getenv("ENABLE_LOGS", "false").lower()

# file backup
SAVE_RECEIPT = os.getenv("SAVE_RECEIPT", "false").lower()