import os

# Telegram
BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")

# Google Sheets
GSHEET_CREDS_JSON = os.getenv("GOOGLE_SHEETS_CREDENTIALS_PATH", "creds.json")

#Openrouter
OPENROUTER_MODEL_NAME = os.getenv("OPENROUTER_MODEL_NAME", "YOUR_OPENROUTER_MODEL_NAME")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "YOUR_OPENROUTER_API_KEY")